services:
  postgres:
    image: postgres:16
    ports:
    - "5432:5432"
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
    - "6379:6379"
    volumes:
    - redis:/data

volumes:
  postgres:
  redis:
