services:
  postgres:
    image: postgres:16
    ports:
    - "5432:5432"
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
    - "6379:6379"
    volumes:
    - redis:/data

  # keygen community edition does not really need a volume to run.
  keygen-web:
    image: keygen/api:v1.4.0
    command: "web"
    ports:
    - "3000:3000"
    env_file:
    - .env
    depends_on:
    - postgres
    - redis

  # keygen community edition does not really need a volume to run.
  keygen-worker:
    image: keygen/api:v1.4.0
    command: "worker"
    env_file:
    - .env
    depends_on:
    - postgres
    - redis

volumes:
  postgres:
  redis:
