name: CI

on:
  push:
    branches:
    - '*'
    - '!HEAD'
    - '!gh-pages'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"
    - run: make govulncheck
      if: ${{ !cancelled() }}
    - run: make lint
      if: ${{ !cancelled() }}
    - run: make test
      if: ${{ !cancelled() }}
    - run: make check-tidy
      if: ${{ !cancelled() }}
    - run: make build
      if: ${{ !cancelled() }}
